[profile.default]
out = 'out'
libs = ['node_modules']
test = 'contracts'
cache_path = 'forge-cache'
src = "contracts"
solc_version = "0.8.28"
via_ir = true
optimizer = true
optimizer_runs = 10
evm_version = "cancun"
[profile.dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"

